### ISSUE TITLE
More .res function

### ISSUE THREAD

**Issue by DarkGD123** [gil-unx/GEBCS#12]
Is it possible to add more files into a .res file?

Like a GUI or some sort to view a .res file content considering the .xml version of them is kinda hard to understand, and which you can just check the contents of the .res files, like the file name, file size, file offset. but not showing their images/models and such. and the tool could do some cool things like **adding new files** or **replacing existing file** or just simply viewing it.

~Dark

**Comment by gil-unx** [comment]
It seems a bit difficult, because the files in res are nested, like xx.res/xx.res/xx.res.
if you edit a local file in res, you have to update the size pointer associated with that file,
and so on until you get to system.res

**Comment by nachotacos69** [comment]
so, basically in the .json file for one .res file, we have to adjust certain offsets here and there to add a new file?

**Comment by DarkGD123** [comment]
***IF*** the .json has more deeper explanation, it would be nice that we can add files in that method anyways

**Comment by nachotacos69** [comment]
yeah, but i think gil-unx should be sufficient for now
