### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by nachotacos69** [gil-unx/GEBCS#2]
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at GEBCS.Tr2Encoder.LoadTxt(String txtName, Int32 count)
   at GEBCS.Tr2Encoder.Utf8(Tr2Info tr2Info)
   at GEBCS.Tr2Encoder..ctor(String fileName)
   at GEBCS.PresRepack.Repack(BW& package, Int64& pointOffset)
   at GEBCS.Program.Repack()
   at GEBCS.Program.Main(String[] args)

**Comment by gil-unx** [comment]
> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>    at GEBCS.Tr2Encoder.LoadTxt(String txtName, Int32 count)
>    at GEBCS.Tr2Encoder.Utf8(Tr2Info tr2Info)
>    at GEBCS.Tr2Encoder..ctor(String fileName)
>    at GEBCS.PresRepack.Repack(BW& package, Int64& pointOffset)
>    at GEBCS.Program.Repack()
>    at GEBCS.Program.Main(String[] args)

Traceback before that apear,

**Comment by nachotacos69** [comment]
alright, i fixed it, also when using COPY1.bat, the screen event text files doesnt exist (JP ver of GEB 1.01)

**Comment by gil-unx** [comment]
> alright, i fixed it, also when using COPY1.bat, the screen event text files doesnt exist (JP ver of GEB 1.01)

okay, later I'll try to see + make move txt bat for the Japanese version

**Comment by nachotacos69** [comment]
hmm, can i ask how to edit .tr2 files

**Comment by gil-unx** [comment]
Well, just edit the 
*.txt file

**Comment by nachotacos69** [comment]
oki, but i did get a ```mismatch txt index```

**Comment by gil-unx** [comment]
I don't know what you edited.  but as long as you doesn't destroy the numbering info, this won't happen.  Understand what you are editing. Compare txt befor and after editing, are there something wrong?
Be carefull with machine translate

**Comment by nachotacos69** [comment]
yeah thanks i kind messed up the numbers and its fixed

**Comment by nachotacos69** [comment]
i dont know if you would agree to this but can try to do dlc extraction and compression (so like i or everyone can see what's inside of the .edat files inside those dlc folders and edit them)

**Comment by nachotacos69** [comment]
> I don't know what you edited. but as long as you doesn't destroy the numbering info, this won't happen. Understand what you are editing. Compare txt befor and after editing, are there something wrong? Be carefull with machine translate

i do manual translation, its kinda weird that i have 50/50 to get a mismatch txt index even tho everything is correct

**Comment by gil-unx** [comment]
Just comparing, the txt. Or give me the txt before & after editing. Are the error from the encoder or something wrong with your edited txt.

**Comment by gil-unx** [comment]
Please note, dont use  basic notepad from window, sometime they changing the encoding txt, changing newline, or add utf-8 BOM on txt.

**Comment by nachotacos69** [comment]
got any idea where to translate the dlc missions?
i cant find them

**Comment by gil-unx** [comment]
What dlc you mean? Can you give me a sample, or , ehem, link to that file 😂

**Comment by nachotacos69** [comment]
also even when you edited the .txt files you kinda still have jp (well some of them... and i found out that .xml has japan texts)

**Comment by nachotacos69** [comment]
> What dlc you mean? Can you give me a sample, or , ehem, link to that file 😂
dlc and the actual game is separated so yeah go check the God Eater Burst dlc here

https://cdromance.com/sony-psp-dlc-list-psp-downloadable-content/

**Comment by gil-unx** [comment]
> .

Well, ge game has a tons of duplicated file, make sure you edited them

**Comment by nachotacos69** [comment]
there are some texts that you cant but its ok

**Comment by gil-unx** [comment]
> got any idea where to translate the dlc missions?
> i cant find them 
> 
> 

well, some *.dat file actually a .pres file, ill update the extractor, for singgle pres file

**Comment by nachotacos69** [comment]
ok then

**Comment by nachotacos69** [comment]
add me on discord if you want -Yamato Nagasaki-#2560

**Comment by nachotacos69** [comment]
some updates: i changed some Japan texts to English texts on npc names and their xmls and they are still japanese but im still investigating

**Comment by nachotacos69** [comment]
i should probably focus on main story translation since some of the texts cant be replaced in game even though i edited their texts

**Comment by gil-unx** [comment]
as I said before, for a kind of npc name, the files are a lot of
duplication.  because each stage/story, load a different file.  make sure
to edit everything

**Comment by nachotacos69** [comment]
yeah

**Comment by nachotacos69** [comment]
![evi1](https://user-images.githubusercontent.com/99103531/153509263-8f1b74c8-1aea-49e5-b9ae-f35a8ec6bfdd.PNG)
alright i've edited the xml files (not in UTF8-BOM) +  i edited the txt of them in UTF8-BOM

![NPJH50352_00003](https://user-images.githubusercontent.com/99103531/153509444-283bb2cf-850a-47f6-a80f-60b958af834b.png)
still same shit happens

**Comment by nachotacos69** [comment]
alright here the zooming bug, yeah it happens in the ENG version too..
![NPJH50352_00000](https://user-images.githubusercontent.com/99103531/153558148-0518028e-835b-4b7d-acce-209aec39746b.png)

**Comment by nachotacos69** [comment]
1. this happens rarely in Medical Check Scene idk why but tbh i only touched the event.txt file
![NPJH50352_00001](https://user-images.githubusercontent.com/99103531/153559050-e4cbd96c-ab01-4e5f-8d5e-ce79985e7cd7.png)
![NPJH50352_00002](https://user-images.githubusercontent.com/99103531/153559089-3cf85a0b-4102-4b94-9d29-466a68b1cd3b.png)
2. yeah this part that ur face isnt shown (which is shown in the original)

**Comment by gil-unx** [comment]
Before you say this as issue, please cek the original game,

**Comment by nachotacos69** [comment]
oh im sorry, these are PPSSPP emulator bugs i forgot to mention lmao

**Comment by nachotacos69** [comment]
and yeah its all good in PSP-2000 👍

**Comment by nachotacos69** [comment]
also do you have the tools to edit the .sprx and .edat files for the dlc (yeah i just want to ask because i cant any tools to get those)

**Comment by nachotacos69** [comment]
So apparently GEB Japan ver DLC is blocking my english translation, forcing the english mission names and description to japanese, probably applies on npc names

**Comment by nachotacos69** [comment]
so any updates?

**Comment by nachotacos69** [comment]
idk if u know about C language but can you check this one https://github.com/nyirsh/GEBUtils

update: gonna send the compiled stuff
