### ISSUE TITLE
Some issue (again)

### ISSUE THREAD

**Issue by nachotacos69** [gil-unx/GEBCS#3]
![issue2](https://user-images.githubusercontent.com/99103531/153781526-2c299f17-3dd8-4e77-b021-af59e1dccb59.PNG)
i did a repack and the other .tr2 files are encoded except for the article.tr2.

**Comment by gil-unx** [comment]
This issue  comes from dlc, i don't have any plans to make a dlc extractor
in the near future.  For now it's better to edit the clean iso.

**Comment by nachotacos69** [comment]
> This issue comes from dlc, i don't have any plans to make a dlc extractor in the near future. For now it's better to edit the clean iso.

I understand, i've been doing some dlc stuff which i did some research, im actually trying my best to manually edit the dlc files so yeah
