### ISSUE TITLE
Possible DLC Extraction and Repack?

### ISSUE THREAD

**Issue by DarkGD123** [gil-unx/GEBCS#8]
Considering the package.rdp uses pres as well inside of it, the dlc as well uses that method but rather in a.. wacky way I suppose, it still uses the `pres` which is cool I suppose.. but I think it is possible since @nachotacos69 did some small documentary about what's inside of the [DLC Files](https://github.com/nachotacos69/WikiEater/blob/main/GOD%20EATER%20BURST%20DLC.md).. although he still has no knowledge to do repacking and unpack methods.. that's why I asked you if you can do it

**Comment by nachotacos69** [comment]
didn't know i got mentioned here lol.. we can't really confirm the tool would be dlc supported since the developer has been inactive on the tool lately

**Comment by nachotacos69** [comment]
what do you think @gil-unx, will it work?

**Comment by DarkGD123** [comment]
Well.. considering @gil-unx is busy on other projects, there are small chances for this tool to be updated for dlc support whatsoever, but to be honest but we might get it soon but it's not on its way there I suppose


Also @nachotacos69 the dlc only uses .vag for aragamis?

**Comment by DarkGD123** [comment]
I used [GEBUtils](https://github.com/nyirsh/GEBUtils) to extract the dlc contents, it did also extract .pres but not extracting the .pres contents itself but sadly the way this tool extract contents are disorganized (only in file names), and then when I simple modify a few texts they would just get corrupted easily, making the tool unreliable for dlc modding/translation

**Comment by nachotacos69** [comment]
yeah.. it can be problem

**Comment by nachotacos69** [comment]
update: i manage to just get some chunks of data of which then attempt to export the data by renaming is either `package.rdp` or `system.res` which is wild, but anyways its a bit wacky to learn and extract the full dlc data, overall it still unstable 💀 


![Screenshot (199)](https://github.com/gil-unx/GEBCS/assets/99103531/dc9e24af-6e98-42b0-912a-b1c7b70eaa2f)
![Screenshot (200)](https://github.com/gil-unx/GEBCS/assets/99103531/598ba897-b8df-4935-be03-997b48a3fb20)

**Comment by nachotacos69** [comment]
Renaming `4a92f06c65fd9bc1536e36e89a065222.edat` as `package.rdp` and renaming `f3594808fb6a0f2123811d0d26b0af74.edat` as `system.res`

extraction is actually okay?
but.. it gets stuck from here...
![Screenshot (205)](https://github.com/gil-unx/GEBCS/assets/99103531/ec11ac7f-c671-4c3c-97c0-439ad2a725a7)

![Screenshot (206)](https://github.com/gil-unx/GEBCS/assets/99103531/29b58cf0-6709-4775-8d41-88b88c9e4f8e)

**Comment by nachotacos69** [comment]
do you have any ideas to fix this? @gil-unx

**Comment by DarkGD123** [comment]
hmm

**Comment by nachotacos69** [comment]
You can find the DLC Downloadable Stuff here @gil-unx: https://cdromance.org/sony-psp-dlc-list-psp-downloadable-content/

**Comment by nachotacos69** [comment]
YouTube keeps deleting the links @gil-unx so yeah, here's the link

**Comment by DarkGD123** [comment]
yeah @gil-unx, i updated my comment on the video, you should see the link there

**Comment by gil-unx** [comment]
> yeah @gil-unx, i updated my comment on the video, you should see the link there

okay be patient i will check soon

**Comment by nachotacos69** [comment]
Take your time, no need to rush

**Comment by gil-unx** [comment]
okay unpacker + repacker done, testing..

**Comment by nachotacos69** [comment]
Okay then 🙏

**Comment by gil-unx** [comment]
please test the new tool

**Comment by nachotacos69** [comment]
I Will report tomorrow, currently I'm on work, which is yeah.. a common thing for me now, but yeah I'll check it tomorrow

**Comment by gil-unx** [comment]
change to NET 8.0
